import 'package:flutter/material.dart';

// Wygenerowane z C:\DOM\Nagłówki. Nazwa poziomu pochodzi z folderu przypisanego do ikony.
const Map<String, String> clockLevelTitles = {
  'img1': 'Zdrowie',
  'img1_1': 'Podstawy zdrowia',
  'img1_1_1': 'Świadomość',
  'img1_1_2': 'Medytacja',
  'img1_1_3': 'Żywienie',
  'img1_1_4': 'Polecane książki',
  'img1_1_4_1': 'Inzynieria wnętrza',
  'img1_1_4_2': 'Karma',
  'img1_1_4_3': 'Polecane Wykłady',
  'img1_1_5': 'Polecane wykłady',
  'img1_2': 'Badania',
  'img1_4': 'Terapie',
  'img1_4_1': 'Oczyszczające wzmocnienie',
  'img1_4_1_1': 'Oczyszczanie z pasożytów',
  'img1_4_1_2': 'Oczyszczanie z Metali ciężkich',
  'img1_4_1_3': 'Sauna',
  'img1_4_1_3_1': 'Sauna sucha (fińska)',
  'img1_4_1_3_3': 'Sauna parowa (łaźnia rzymska)',
  'img1_4_1_4': 'Morsowanie',
  'img1_4_1_5': 'Dotlenienie',
  'img1_4_1_6': 'Uziemienie',
  'img1_4_1_7': 'Konchowanie',
  'img1_4_1_8': 'Kąpiele',
  'img1_4_1_8_1': 'Kąpiel w soli Epsom',
  'img1_4_1_8_10': 'Kąpiel z sodą oczyszczoną',
  'img1_4_1_8_2': 'Kąpiel Kleopatry',
  'img1_4_1_8_3': 'Kąpiel owsiana na podrażnienia',
  'img1_4_1_8_4': 'Kąpiel ziołowa (relaks lub przeziębienie)',
  'img1_4_1_8_5': 'Kąpiel rozgrzewająca z olejkami eterycznymi',
  'img1_4_1_8_6': 'Kąpiel Imbirowa (Rozgrzewająca i Przeciwprzeziębieniowa)',
  'img1_4_1_8_7': 'Kąpiel z Piołunu Chińskiego  Mugwort',
  'img1_4_1_8_8': 'Kąpiel Różana (Relaksująca i Wzmacniająca)',
  'img1_4_1_8_9':
      'Kąpiel ze Skórki Mandarynki i Imbiru (Na Wilgoć i Zmęczenie)',
  'img1_4_10': 'Syropy',
  'img1_4_11': 'Glinka',
  'img1_4_12': 'Masło klarowne',
  'img1_4_13': 'Akupunktura',
  'img1_4_14': 'Srebro koloidalne',
  'img1_4_15': 'Olej konopny',
  'img1_4_2': 'Odczulające',
  'img1_4_3': 'Psychologiczne',
  'img1_4_3_5': 'Linki',
  'img1_4_4': 'Kręgosłup',
  'img1_4_5': 'Krople Dr. Bacha',
  'img1_4_5_1': 'Przewodnik',
  'img1_4_5_2': '7 Typów osobowości',
  'img1_4_5_3': '7 Typów dysharmoni',
  'img1_4_5_4': 'Opis Kropli',
  'img1_4_5_4_1': 'Lęk',
  'img1_4_5_4_2': 'Niezdecydowanie i niepewność',
  'img1_4_5_4_3': 'Zobojętnienie na świat',
  'img1_4_5_4_4': 'Samotność',
  'img1_4_5_4_5': 'Nadwrażliwość',
  'img1_4_5_4_6': 'Rozpacz i rezygnacja',
  'img1_4_5_4_7': 'Nadmierna troska o dobro innych',
  'img1_4_5_4_8': 'Lek I Pomocy',
  'img1_4_6': 'Mięśnie',
  'img1_4_7': 'Bańki',
  'img1_4_8': 'Zioła',
  'img1_4_9': 'Witaminy',
  'img2': 'Napoje i żywność',
  'img2_1': 'Got wg 5 smaków',
  'img2_1_1': 'Dlaczego wg 5 smaków',
  'img2_1_2': 'Zupy',
  'img2_1_2_1': 'Zupa śniadaniowa',
  'img2_1_2_10': 'Neapolitańska',
  'img2_1_2_11': 'Kapuśniak',
  'img2_1_2_12': 'Zacierka',
  'img2_1_2_13': 'Z botwiny',
  'img2_1_2_14': 'Pieczarkowa',
  'img2_1_2_15': 'Z zielonego groszku',
  'img2_1_2_16': 'Grochówka z lanymi kluskami',
  'img2_1_2_17': 'Z porów miksowana',
  'img2_1_2_18': 'Jarzynowa miksowana',
  'img2_1_2_19': 'Selerowa miksowana',
  'img2_1_2_2': 'Rosół wołowo drobiowy',
  'img2_1_2_20': 'Wiosenna z zieleniny',
  'img2_1_2_21': 'Jarzynowa',
  'img2_1_2_22': 'Szczawiowa',
  'img2_1_2_23': 'Żurek',
  'img2_1_2_24': 'Jesienna',
  'img2_1_2_25': 'Barszcz czysty',
  'img2_1_2_26': 'Z soczewicy',
  'img2_1_2_27': 'Z soczewicą i ciecieżycą',
  'img2_1_2_28': 'Fasolowa śródziemnomorska',
  'img2_1_2_29': 'Cytrynowa',
  'img2_1_2_3': 'Pomidorowa',
  'img2_1_2_30': 'Z dyni',
  'img2_1_2_31': 'Czosnkowa',
  'img2_1_2_4': 'Lane kluski',
  'img2_1_2_5': 'Barszcz ukraiński',
  'img2_1_2_6': 'Fasolowa',
  'img2_1_2_7': 'Krupnik',
  'img2_1_2_8': 'Cebulowa',
  'img2_1_2_9': 'Grochówka',
  'img2_1_3': 'Dania Mięsne i Mięsno Jarzynowe',
  'img2_1_3_1': 'Wieprzowina',
  'img2_1_3_1_1': 'Klopsiki',
  'img2_1_3_1_2': 'Kotlet mielony',
  'img2_1_3_1_3': 'Kotlet schabowy panierowany',
  'img2_1_3_1_4': 'Pieczeń wieprzowa',
  'img2_1_3_1_5': 'Schab pieczony',
  'img2_1_3_1_6': 'Schab z bekonem i pieczarkami',
  'img2_1_3_1_7': 'Wieprzowina z jarzynami',
  'img2_1_3_2': 'Wołowina',
  'img2_1_3_2_1': 'Pieczeń wołowa',
  'img2_1_3_2_2': 'Zrazy wołowe zawijane',
  'img2_1_3_2_3': 'Wołowina z kapustą',
  'img2_1_3_2_4': 'Mięso wołowe z jarzynami',
  'img2_1_3_3': 'Żeberka',
  'img2_1_3_3_1': 'Żeberka z kapustą',
  'img2_1_3_3_2': 'Żeberka na ostro',
  'img2_1_3_3_3': 'Żeberka duszone na słodko',
  'img2_1_3_3_4': 'Żeberka duszone na ostro',
  'img2_1_3_4': 'Kurczak',
  'img2_1_3_4_1': 'Kurczak pieczony ( tradycyjny )',
  'img2_1_3_4_2': 'Kurczak panierowany',
  'img2_1_3_4_3': 'Kurczak pieczony w cebuli',
  'img2_1_3_4_4': 'Kurczak nadziewany pieczony',
  'img2_1_3_4_5': 'Pierś z kurczaka z szałwią i wódką',
  'img2_1_3_4_6': 'Pierś z kurczaka z ananasem',
  'img2_1_3_5': 'Kaczka',
  'img2_1_3_5_23': 'Kaczka nadziewana pieczona',
  'img2_1_3_6': 'Indyk',
  'img2_1_3_6_24': 'Indyk nadziewany pieczony',
  'img2_1_3_7': 'Ryby',
  'img2_1_3_7_1': 'Ryba smażona filet',
  'img2_1_3_7_2': 'Ryba duszona w jarzynach',
  'img2_1_3_8': 'Zaprawa do mięs',
  'img2_1_3_9': 'Sosy',
  'img2_1_3_9_1': 'Sos beszamelowy zielony',
  'img2_1_3_9_2': 'Sos potrawkowy do kurczaka z rosołu',
  'img2_1_4': 'Jarzyny do obiadu',
  'img2_1_5': 'Dania Jarskie',
  'img2_1_5_1': 'Ziemniaki z wody',
  'img2_1_5_10': 'Krokiety z kaszy jęczmiennej',
  'img2_1_5_11': 'Risotto',
  'img2_1_5_2': 'Naleśniki',
  'img2_1_5_3': 'Nadzienie mięsno warzywne',
  'img2_1_5_4': 'Nadzienie ze słodkiej kapusty',
  'img2_1_5_5': 'Nadzienie słodkie z twarogu',
  'img2_1_5_6': 'Smażone banany',
  'img2_1_5_7': 'Kluski serowe',
  'img2_1_5_8': 'Omlet z pieczarkami',
  'img2_1_5_9': 'Placki ziemniaczane',
  'img2_1_6': 'Potrawy kolacyjne',
  'img2_1_6_1': 'Kiełbasa po węgiersku',
  'img2_1_6_2': 'Sos z kukrurydzą do makaranu',
  'img2_1_6_3': 'Pizza',
  'img2_1_6_4': 'Sos tatarski',
  'img2_1_6_5': 'Golonka w galarecie',
  'img2_1_6_6': 'Pasztet domowy',
  'img2_1_6_7': 'Smalec z przyprawami',
  'img2_1_7': 'Sałatki',
  'img2_1_8': 'Jak oczyścić żywność',
  'img2_2': 'Napoje',
  'img2_2_1': 'Żywa woda',
  'img2_2_2': 'Jak oczyścić owoce',
  'img2_2_3': 'Herbata',
  'img2_2_3_1': 'Herbata nr I',
  'img2_2_3_2': 'Herbata naturalna I',
  'img2_2_3_3': 'Herbata 2aturalna II',
  'img2_2_3_4': 'Heraba daktylowa',
  'img2_2_3_5': 'Herbata przy zastojach kolkach',
  'img2_2_4': 'Kawa',
  'img2_2_5': 'Soki',
  'img2_2_5_1': 'Burak cytryna seler',
  'img2_2_5_10': 'Owoce tropikalne',
  'img2_2_5_11': 'Seler jarmuż',
  'img2_2_5_12': 'Jarmuż ogórek cytryna',
  'img2_2_5_2': 'Burak marchew jabłko imbir',
  'img2_2_5_3': 'Seler burak',
  'img2_2_5_4': 'Marchew imbir cytryna',
  'img2_2_5_5': 'Marchew jabłko pietruszka',
  'img2_2_5_6': 'Jabłko cynamon imbir',
  'img2_2_5_7': 'Pomarańcz marchew ananas',
  'img2_2_5_8': 'Pomidor papryka seler',
  'img2_2_5_9': 'Grejpfrut kiwi jabłko',
  'img2_2_6': 'Koktajle',
  'img2_2_6_1': 'Koktajl owocowo-jogurtowy',
  'img2_2_6_2': 'Koktajl z papai i fig',
  'img2_2_6_3': 'Koktajl mango i liczi',
  'img2_2_6_4': 'Koktail Gęsty Owocowy moc',
  'img2_2_6_5': 'Roślinne „mleko” migdałowe',
  'img2_2_7': 'Kompoty',
  'img2_2_7_1': 'Kompot z jabłek miętą i miodem',
  'img2_2_7_2': 'Kompot z gruszek i miodem',
  'img2_2_7_3': 'Kompot z rabarberu i miodem',
  'img2_2_7_4': 'Kompot z suszu i miodem',
  'img2_2_7_5': 'Kompot Jabłkowo jeżynowy',
  'img2_2_8': 'Jogurty',
  'img2_3': 'Ciasta',
  'img2_4': 'Własne Przetwory',
  'img2_5': 'Przepisy Rozgrzewające i wzmacniające',
  'img3': 'Środki higieniczne',
  'img3_1': 'Mydła',
  'img3_2': 'Płyn do kąpieli',
  'img3_3': 'Szmpon do włosów',
  'img3_4': 'Środki do higieny intymnej',
  'img3_4_1': 'Aloesowo mydlany',
  'img3_4_2': 'Z sodą',
  'img3_4_3': 'Na infekcje',
  'img3_5': 'Balsam do ciała',
  'img3_6': 'Odżywki do włosów',
  'img3_6_1': 'Bananowo miodowa',
  'img3_6_2': 'Płukanka Aloesowo miętowa',
  'img3_6_3': 'Z awokado i miodem',
  'img3_7': 'Płyn antybakteryjny',
  'img3_8': 'Pasty do zebow',
  'img4': 'Środki czystości',
  'img4_1': 'Tabletki do zmywarki',
  'img4_2': 'Proszek do prania',
  'img4_2_1': 'Mocny uniwersalny',
  'img4_2_2': 'Do prania białego',
  'img4_2_3': 'Delikatny dla alergików',
  'img4_3': 'Płyn do mycia naczyń',
  'img4_3_1': 'Płyn z sodą kalcynowaną (silniejszy)',
  'img4_3_2': 'Płyn z solą',
  'img4_4': 'Płyn do płukania ubrań',
  'img4_4_1': 'Lawendowy z octem',
  'img4_4_2': 'Kwaskowy płyn cytrynowy',
  'img4_4_3': 'Delikatny płyn sodowo-octowy',
  'img4_5': 'Płyn do mycia szyb',
  'img4_5_1': 'Płyn z octem',
  'img4_5_2': 'Płyn z alko',
  'img4_5_3': 'Płyn z cytryna',
  'img4_6': 'Płyn do podług',
  'img4_6_1': 'Octowo cytrynowy',
  'img4_6_2': 'Do podłóg drewnianych',
  'img4_6_3': 'Odświerzający do dużych zabrudzeń',
  'img4_7': 'Odświeżacze',
  'img4_7_1': 'Szybki uniwersalny',
  'img4_7_2': 'Neutralizator zapachów',
  'img4_7_3': 'Z patyczkami długotrwały',
  'img5': 'Ogródek',
  'img5_1': 'Zaprojektuj ogródek',
  'img5_3': 'Naturalne nawozy',
  'img5_3_1': 'Obornik',
  'img5_3_1_1': 'Rodzaje obornika',
  'img5_3_1_2': 'Nawożenie kiedy i jak',
  'img5_3_1_3': 'Płynny nawóz',
  'img5_3_1_4': 'Obornik granulowany',
  'img5_3_10': 'Drożdże piekarskie',
  'img5_3_11': 'Woda po płukaniu ryżu',
  'img5_3_12': 'Popiół z drewna',
  'img5_3_2': 'Kompost',
  'img5_3_3': 'Skórki bananowe',
  'img5_3_4': 'Fusy kawowe',
  'img5_3_5': 'Woda po gotowaniu warzyw',
  'img5_3_6': 'Roślinny napar z chwastów',
  'img5_3_7': 'Obierki warzywne',
  'img5_3_8': 'Skorupki jajek',
  'img5_3_9': 'Cebula i czosnek',
  'img5_4': 'Naturalne opryski',
  'img6': 'Kupujemy u rolnika',
  'img7': 'Polecane',
  'img7_5': 'Samowystarczalni',
  'img8': 'Moje menu',
  'img8_1': 'Moje zakupy',
  'img8_2': 'Do zrobienia',
  'img8_3': 'Inżynieria mojego czasu',
  'img8_4': 'Ulubione',
  'img8_5': 'Moje wydatki',
  'img8_6': 'Moje oszczędności',
};

String clockLevelBaseFromImagePath(String path) {
  final fileName = path.replaceAll('\\', '/').split('/').last;
  final base = fileName.replaceAll(RegExp(r'\.[^.]+$'), '');
  return base.split('_g').first;
}

String clockTitleForImagePath(String path) {
  final base = clockLevelBaseFromImagePath(path);
  final knownTitle = _knownTitleForBase(base);
  if (knownTitle != null) {
    return knownTitle;
  }

  return 'Zadanie';
}

String? _knownTitleForBase(String base) {
  var candidate = base;

  while (candidate.isNotEmpty) {
    final title = clockLevelTitles[candidate];
    if (title != null) {
      return title;
    }

    final lastSeparator = candidate.lastIndexOf('_');
    if (lastSeparator == -1) {
      break;
    }

    candidate = candidate.substring(0, lastSeparator);
  }

  return null;
}

IconData clockIconForImagePath(String path) {
  return Icons.auto_awesome_rounded;
}

String levelImagePathForImagePath(String path) {
  final base = clockLevelBaseFromImagePath(path);
  return 'assets/$base.webp';
}

String clockIconPathForImagePath(String path) {
  final base = clockLevelBaseFromImagePath(path);
  return 'assets/clock_icons/$base.webp';
}
